version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SURREALDB_URL=http://db:8000
      - SURREALDB_USER=root
      - SURREALDB_PASS=root
      - SURREALDB_NS=spottisahko
      - SURREALDB_DB=main
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    command: surreal start --log info --user root --pass root file:./data/database.db
    volumes:
      - surrealdb_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  surrealdb_data: